### ISSUE TITLE
[feat] 백엔드 서버 CI/CD 배포 라인 구축

### ISSUE THREAD

**Issue by nakyeonko3** [byulhook/travely#16]
### CI/CD 배포 라인 설정
- ec2, github aciton, express 를 이용해서 백엔드 서버만 배포를 할 예정.
- main 브랜치에 커밋이 될 때마다 자동으로 변경된 내용이 ec2 서버에 반영되고 재배포되도록 설정할 예정.

### 참고
https://hackernoon.com/lang/ko/github-%EB%B0%8F-aws-ec2%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-cicd-%ED%8C%8C%EC%9D%B4%ED%94%84%EB%9D%BC%EC%9D%B8%EC%9D%84-%EC%83%9D%EC%84%B1%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

### ✅ 작업 목록

- [x] ec2 ci/cd express 배포하기
	- [x] ec2 서버 인스턴스 만들고 express 작동하는지 확인하기
	- [x] github action으로 배포 세팅하기
	- [x] 배포 하기
	- [x] 배포 확인하기

- [x] 배포 workflow 설정 작업
- [x] 실제 배포가 일어나는지 확인하고 테스트 하기

**Comment by Sonseongoh** [comment]
훌륭합니다 낙연님
